name: Create a repository dispatch for cwtools/cwtools-cache-files
on: push 

jobs:
  stellaris_dispatch:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.CWTOOLSBOT_TOKEN }}
    steps:
    - run: |
        curl --fail -u "cwtoolsbot@protonmail.com:${GITHUB_TOKEN}" -X POST https://api.github.com/repos/cwtools/cwtools-cache-files/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        --data "{\"event_type\": \"build-cache-stellaris\"}"
